---
- name: Deploy app
  hosts: app
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: 5c217c565c1122c5343dc0514c116ae816c17ca2
    notify: reload puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit

  handlers:
  - name: reload puma
    become: True
    systemd: name=puma state=restarted
